Repository realjaidhaliwal/Snake, pull requests merged in 2022-04, with the labels that each got.

#11 Create unit test framework and fix workflow for GUI tests
  .github/workflows/unit-tests.yml
  .gitignore
  pom.xml
  src/test/java/com/snake/game/WindowTest.java
Labels: bug, enhancement

#12 Create Tests
  src/main/java/com/snake/game/DataOfSquare.java
  src/main/java/com/snake/game/SquarePanel.java
  src/test/java/com/snake/game/DataOfSquareTest.java
  src/test/java/com/snake/game/KeyboardListenerTest.java
  src/test/java/com/snake/game/SquarePanelTest.java
  src/test/java/com/snake/game/TupleTest.java
Labels: help wanted

#14 Revert "Create Tests"
  src/main/java/com/snake/game/DataOfSquare.java
  src/main/java/com/snake/game/SquarePanel.java
  src/test/java/com/snake/game/DataOfSquareTest.java
  src/test/java/com/snake/game/KeyboardListenerTest.java
  src/test/java/com/snake/game/SquarePanelTest.java
  src/test/java/com/snake/game/TupleTest.java
Labels: enhancement

#13 Two Player Mode
  src/main/java/com/snake/game/KeyboardListener.java
  src/main/java/com/snake/game/Main.java
  src/main/java/com/snake/game/MainMenu.java
  src/main/java/com/snake/game/ThreadsController.java
  src/main/java/com/snake/game/Tuple.java
  src/main/java/com/snake/game/Window.java
Labels: enhancement

#15 Review: Create Tests
  src/main/java/com/snake/game/DataOfSquare.java
  src/main/java/com/snake/game/SquarePanel.java
  src/test/java/com/snake/game/DataOfSquareTest.java
  src/test/java/com/snake/game/KeyboardListenerTest.java
  src/test/java/com/snake/game/SquarePanelTest.java
  src/test/java/com/snake/game/TupleTest.java
  src/test/java/com/snake/game/WindowTest.java
Labels: enhancement

#17 Updated Variable Name
  src/test/java/com/snake/game/KeyboardListenerTest.java
Labels: enhancement

#19 Update Window.java
  src/main/java/com/snake/game/Window.java
Labels: bug

#20 Update MainMenu.java
  src/main/java/com/snake/game/MainMenu.java
  src/main/java/com/snake/game/Window.java
Labels: enhancement

#18 Pause Functionality
  src/main/java/com/snake/game/KeyboardListener.java
  src/main/java/com/snake/game/ThreadsController.java
Labels: enhancement

#23 Added Restart Button and Score
  src/main/java/com/snake/game/ThreadsController.java
  src/main/java/com/snake/game/Window.java
  src/test/java/com/snake/game/PauseTest.java
Labels: enhancement
